	git checkout html5/.idea/.name
	git checkout html5/.idea/encodings.xml
	git checkout html5/.idea/html5.iml
	git checkout html5/.idea/libraries/sass_stdlib.xml
	git checkout html5/.idea/misc.xml
	git checkout html5/.idea/modules.xml
	git checkout html5/.idea/scopes/scope_settings.xml
	git checkout html5/.idea/vcs.xml
	git checkout html5/.idea/workspace.xml
